name: Teste Flask no GitHub Actions

on:
  push:
    branches: [ main ]

jobs:
  test-flask:
    runs-on: ubuntu-latest

    steps:
    - name: Fazer checkout do código
      uses: actions/checkout@v3

    - name: Configurar Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Iniciar servidor Flask em background
      run: |
        nohup python app.py > flask.log 2>&1 &
        # espera subir
        sleep 8

    - name: Testar endpoint e mostrar saída
      run: |
        echo "Resposta do servidor:"
        curl -i http://127.0.0.1:5000 || exit 1

    - name: Mostrar logs completos do Flask
      if: failure() || success()
      run: |
        echo "=== flask.log ==="
        cat flask.log
